### ISSUE TITLE
Document/automate release process

### ISSUE THREAD

**Issue by twolfson** [slack-for-linux/slack-for-linux#59]
Now that multiple people can publish to `npm`, we should have a consistent release process. We are pretty good with respect to `git tag` and `npm publish` but have missed a few `CHANGELOG.md` updates.

@wlaurance What's the current process that you follow?

**Comment by wlaurance** [comment]
I usually do `npm version [major,minor,patch] && git push origin master --tags && npm publish`

Isn't there a tool automatically build the `CHANGELOG.md`? If so, we should add that to the deployment procedure.

**Comment by twolfson** [comment]
I usually do CHANGELOG by hand but if you want to automate it based off of `git` commits, then I am all for it. There are a good amount of tools for that:

http://node-modules.com/search?q=changelog

**Comment by wlaurance** [comment]
https://github.com/lalitkapoor/github-changes#generate-changelog-via-pull-request

**Comment by twolfson** [comment]
Tried out the link you provided. It works pretty well but will miss out on all things committed outside of a PR. If we are cool with that, then I will open up a PR with a `release.sh` and the discussed flow:

```bash
./node_modules/.bin/github-changes --owner slack-for-linux --repository slack-for-linux --only-pulls --title "slack-for-linux changelog" --use-commit-body
```

```bash
## slack-for-linux changelog

### upcoming (2015/06/02 06:18 +00:00)
- [#63](https://github.com/slack-for-linux/slack-for-linux/pull/63) Remove line from readme (@wlaurance)

### v1.4.2 (2015/05/28 15:20 +00:00)
- [#52](https://github.com/slack-for-linux/slack-for-linux/pull/52) Locked down nw.js version (@twolfson)

### v1.4.1 (2015/05/05 22:44 +00:00)
- [#45](https://github.com/slack-for-linux/slack-for-linux/pull/45) Add better install logging and fixed global nested npm install (@twolfson)
- [#41](https://github.com/slack-for-linux/slack-for-linux/pull/41) Change the app name (@wlaurance)

...
```

**Comment by wlaurance** [comment]
I think this will work because all things will go through a PR now. If you could make this PR with `release.sh`, that would be awesome.
