### ISSUE TITLE
Enforce collaborative workflow

### ISSUE THREAD

**Issue by twolfson** [slack-for-linux/slack-for-linux#62]
@wlaurance I am noticing a few cowboy commits/pushes on `master`.

https://github.com/slack-for-linux/slack-for-linux/commit/e210c78e94a2f3f45ab4aa4d1f9bb559f322c196

https://github.com/slack-for-linux/slack-for-linux/commit/2dd2d089787ecab37303d07acbb1cc1ccd122cb6

Since we have multiple collaborators, we should consider always having a PR for any changes on `master`. This will guarantee that every change has 2 sets of eyes and catches any one-off issues. For example, too many blank lines here:

https://github.com/slack-for-linux/slack-for-linux/commit/e210c78e94a2f3f45ab4aa4d1f9bb559f322c196#diff-04c6e90faac2675aa89e2176d2eec7d8R68

**Comment by wlaurance** [comment]
OK, will do.

**Comment by twolfson** [comment]
Cool, thanks =)
