### ISSUE TITLE
Direct Message the App Crashes

### ISSUE THREAD

**Issue by fabiokiatkowski** [slack-for-linux/slack-for-linux#76]
Problem being seen is that every direct message I receive the app crashes, the message is not delivered and on console does not appear any message.

Expected behavior on receive direct message the message should be delivered and the app still working.

--

Information about OS:

npm --version: 2.2.0
node --version: v0.10.35
OS: 3.16.7.1-1-MANJARO
Window Manager: i3m

**Comment by twolfson** [comment]
That is very strange behavior. Have you always received this issue or did it recently start occurring?

Also, what version of `slack-for-linux` are you running?

**Comment by fabiokiatkowski** [comment]
I installed the slack-for-linux today, the version is 1.6.2
Yes, this issue occurs on every message.
I tried to open with sudo permission, maybe could be some permissions but still occurs.

**Comment by twolfson** [comment]
We recently added audio notification support which would trigger upon receiving a message. Can you try installing `1.5.x`?

```bash
npm install -g slack-for-linux@1.5.x
```

**Comment by fabiokiatkowski** [comment]
Done!
I installed 1.5.x and this issue don't occurs. Everything is OK!

**Comment by twolfson** [comment]
Cool, so the issue is something between your Chrome's `libffmpegsumo.so` and `nw.js`. If you receive a DM on https://my.slack.com/ are there any issues?

**Comment by bronzdoc** [comment]
@fabiokiatkowski type <code>about:version</code> in chrome and tell us what's your chrome version please, thanks.

**Comment by fabiokiatkowski** [comment]
@twolfson when I use the web client everything is normal even the sound notification.
@bronzdoc below is the chrome version...

--
**Google Chrome**	40.0.2214.95 (Official Build) 
**Revision**	9db0b11598bbd4519c4de00146fa8b91a184aed6-refs/branch-heads/2214_85@{#9}
**OS**	Linux

**Comment by twolfson** [comment]
Your Chrome seems to be behind by a few versions. I am on:

```
Google Chrome	43.0.2357.124 (Official Build) (64-bit)
Revision	d49eb48dfb64b379fdc61282ceca602acbc9065d-refs/branch-heads/2357@{#467}
OS	Linux 
```

Can you upgrade Chrome and re-install `slack-for-linux`? We import the `libffmpegsumo.so` for audio support from Chrome.

```bash
# After upgrading Chrome
npm install -g slack-for-linux@latest
```

**Comment by fabiokiatkowski** [comment]
Done and Works!!!
Thanks @twolfson !

**Comment by twolfson** [comment]
Awesome! Thanks @bronzdoc for pointing us in the right direction with the Chrome version =)
